/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IndexAside: typeof import('./src/components/indexStructure/indexAside.vue')['default']
    IndexHeader: typeof import('./src/components/indexStructure/indexHeader.vue')['default']
    LoadingBar: typeof import('./src/components/generalComponent/loadingBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TryRoot: typeof import('./src/components/indexStructure/indexMain/tryRoot.vue')['default']
    Welcome: typeof import('./src/components/indexStructure/indexMain/welcome.vue')['default']
  }
}

