const express = require("express");
const router = express.Router();
const tableHandler = require("../router_handler/table");
router.get("/chum", tableHandler.chum);
router.get("/tname", tableHandler.tname);
router.get("/estimate", tableHandler.estimate);
router.get("/room", tableHandler.room);
router.post("/chum/delete", tableHandler.chumDelete);
router.get("/ceiling", tableHandler.getFloorCount);
router.post("/room/add", tableHandler.addRoom);
router.get("/admin/floor/search", tableHandler.adminFloorSearch);
router.post("/room/ban", tableHandler.banRoom);
router.post("/room/use", tableHandler.useRoom);
router.post("/floor/push", tableHandler.pushFloor);
router.post("/floor/ban", tableHandler.banFloor);
router.post("/floor/extend", tableHandler.extendFloor);
router.post("/floor/reduce", tableHandler.reduceFloor);
router.post("/floor/use", tableHandler.useFloor);
router.post("/floor/edit", tableHandler.editRoom);
router.get("/flat", tableHandler.flat);
router.post("/flat/add", tableHandler.addFlat);
router.post("/chum/leave", tableHandler.chumLeave);
router.post("/chum/back", tableHandler.chumBack);
module.exports = router;
